apiVersion: k8s.fabkli.ch/v1
kind: Fdeployment
metadata:
  name: goheader
  namespace: goheader
spec:
  path: "/"
  replicas: 1
  port: 8000
  tag: "latest"
  image: "goheader"
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 128Mi
  healthCheck:
    livenessProbe:
      path: "/"
    readinessProbe:
      path: "/"
  host: "goheader.fabkli.ch"